Clarification on Thread Intro
manjugv/specification pull request #13
Opened 2020-02-04 19:18 UTC by manjugv

Address https://github.com/openshmem-org/specification/issues/134

2020-02-04 20:59 UTC, abouteiller approved these changes

2020-02-05 17:39 UTC, manjugv commented
@agrippa @minsii @swpoole @jamesaross @tonycurtis Can you please review?

2020-02-05 17:46 UTC, agrippa requested changes

2020-02-05 17:46 UTC, agrippa commented on content/threads_intro.tex
> +are thread-safe .i.e., any two concurrently running threads may make \openshmem calls.
I think there's some whitespace issues. How about just:

are thread-safe. That is, any two concurrently running threads may make \openshmem calls.

2020-02-05 18:50 UTC, minsii commented
Approve with Max's patch.

2020-02-05 20:45 UTC, tonycurtis approved these changes

2020-02-06 15:12 UTC, agrippa commented
LGTM

2020-02-10 16:10 UTC, jamesaross commented
Best to avoid the confusing language. Approved.

2020-02-14 15:35 UTC, minsii approved these changes

2020-02-14 15:56 UTC, tonycurtis approved these changes

2020-02-15 19:19 UTC, swpoole commented
Looks good to me.

2020-02-16 17:14 UTC, manjugv commented
Thanks committee. We have approvals now and I will merge.

2020-02-16 17:15 UTC, merged